spring:
  application:
    name: SpringCache
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:cache_db
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
